spring.application.name=apollo-study-one

# 1. \u542F\u7528 Apollo
app.id=apollo-study-one
apollo.bootstrap.enabled = true

# 2. \u4F60\u7684 Apollo \u670D\u52A1\u5730\u5740\uFF08Windows \u672C\u5730\u56FA\u5B9A\u8FD9\u4E2A\uFF09
apollo.meta = http://localhost:8080

# 3. \u5E94\u7528ID\uFF08\u5FC5\u987B\u548C Apollo \u540E\u53F0\u521B\u5EFA\u7684 AppID \u4E00\u81F4\uFF09
apollo.app.id = apollo-study-one

# 4. \u52A0\u8F7D\u7684\u73AF\u5883\uFF08\u672C\u5730\u9ED8\u8BA4 dev\uFF09

apollo.cluster=jiangxi
#apollo.bootstrap.namespaces = application
apollo.bootstrap.namespaces = mysql_connection,redis_connection

# 5. \u5F00\u542F\u81EA\u52A8\u66F4\u65B0\u914D\u7F6E\uFF08\u4FEE\u6539\u540E\u4E0D\u7528\u91CD\u542F\u9879\u76EE\uFF09
apollo.autoUpdateInjectedSpringProperties = true

server.port=8068
